spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dungeon_and_ecalora_db
    username: postgres
    password: Miniblop6
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
